name: build Windows
on: [push]
jobs:
  build:
    name: Build Windows
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch -m clone
        env:
          GITHUB_TOKEN: ${{secrets.DEPS_PAT}}

      - name: create cmake cache with Visual Studio 2022
        run: cmake  -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE="Debug" .
        working-directory: src/

      - name: cmake build
        run: cmake --build . --clean-first
        working-directory: src/

      - uses: actions/upload-artifact@v2
        with:
          name: runtime Windows Library
          path: |
            src/runtime.lib
