name: build mac os
on: [push]
jobs:
  build:
    name: Build MacOS
    runs-on: macos-10.15
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Setup cmake
        uses: jwlawson/actions-setup-cmake@v1.12
        with:
          cmake-version: "3.22.x"

      - name: deps fetch dependencies
        run: go run github.com/piot/deps/src/deps@main fetch -m clone
        env:
          GITHUB_TOKEN: ${{ secrets.DEPS_PAT }}

      - name: create cmake cache
        run: cmake -DCMAKE_BUILD_TYPE=Release .
        working-directory: src/

      - name: cmake build
        run: cmake --build . --clean-first
        working-directory: src/

      - uses: actions/upload-artifact@v2
        with:
          name: Swamp Runtime MacOS
          path: |
            src/bin/runtime-example
            src/lib/libswamp-runtime.a
